### PR TITLE
Improvements | notify-send | Urgerncy | Which | BSD

### PR DESCRIPTION
**Pull request by GiorgosXou**
https://github.com/ms7m/notify-py/blob/f748189a2e8b4b147fcbf1acb6912c944d687671/notifypy/os_notifiers/linux.py#L33

* ***Added:*** notification urgency *(low, normal, critical)* for `notify-send`
* ***Fixed:*** `notify-send`, now is being used as the first choice if installed
* ***Fixed:*** OSs like [BSD](https://github.com/ms7m/notify-py/issues/13) now default under the linux-behavioural category
* ***Fixed:*** issue under windows with extra `kwargs` that resulted in error 
* ***Removed:*** `linux_fallback_libnotify`, no more need for it
* ***Replaced:*** functions with the in-built `shutil.which` function

***PS.** Tried not to be messy with the code and respect your overall structural patterns. It has been tested and works fine both on linux and on windows (+the in-built `shutil.which` function works with BSD too)*

### CODE REVIEW

**Comment by GiorgosXou** [comment]
`6 changes` + `1 for the improvments` + `0.3.31` = `0.3.38` 

Removal of `linux_fallback_libnotify` wont effect users that have forced a fallback to libnotify

**Comment by ms7m** [comment]
This looks really good, and I'll merge these changes as well as some overdue patches things such as #40 and PRs #39 !

**Comment by ms7m** [comment]
Don't worry about the tests either, that's also overdue for some changes :-)

**Comment by GiorgosXou** [comment]
* https://github.com/ms7m/notify-py/issues/40 seems to be already fixed https://github.com/ms7m/notify-py/blob/f748189a2e8b4b147fcbf1acb6912c944d687671/pyproject.toml#L16
* I just merged the change of https://github.com/ms7m/notify-py/pull/39
* https://github.com/ms7m/notify-py/pull/37 should be closed. *(function has been replaced by the in-built `shutil.which`)*
* ✔️ Tested briefly

**Comment by ms7m** [comment]
Fantastic!! Thanks so much -- I'm gonna do a PR ( #48 ) to fix up the tests and fix the issue in #46 and we can go ahead and publish this

**Comment by GiorgosXou** [comment]
Done :heavy_check_mark:

**Comment by GiorgosXou** [comment]
*I'm working on a project that I want to upload in the next days, which uses this package... So.. would you mind to speed up a bit the process of publishing?*

**Comment by ms7m** [comment]
Sure -- Sorry for the delay. Please pull in the latest changes from ``master`` and I can merge/publish this version.

**Comment by GiorgosXou** [comment]
Done ✔️

**Comment by ms7m** [comment]
Fantastic, I really do appreciate it! 🎉

**Pull request merged**
